name: OTF Testing

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test on ${{ matrix.browser }}
    permissions: write-all
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - browser: firefox
            port: 4444
            image: selenium/standalone-firefox:latest

          - browser: chrome
            port: 4445
            image: selenium/standalone-chrome:latest

          - browser: edge
            port: 4446
            image: selenium/standalone-edge:latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Create isolated network
        run: docker network create --driver bridge isolated

      - name: Deploy AUT
        run: docker build -t my-php-site:latest .

      - name: Run AUT
        run: docker run --network=isolated -p 80:80 --name docker-apache -d my-php-site:latest

      - name: Get AUT URL
        run: |
          URL=http://$(ip -f inet -o addr show docker0 | awk '{print $4}' | cut -d '/' -f 1)
          echo "URL=$URL" >> $GITHUB_ENV

      - name: Check AUT Url
        run: curl ${{ env.URL }}

      - name: Start Selenium
        run: |
          docker run \
          --network=isolated \
          -d \
          -p ${{ matrix.port }}:4444 \
          -v /dev/shm:/dev/shm \
          --name selenium-${{ matrix.browser }} \
          ${{ matrix.image }}

      - name: Wait for Selenium Hub
        run: sh wait.sh

      - name: Check Selenium Hub
        run: curl http://localhost:${{ matrix.port }}

      - name: Install Selenium Client
        run: pip install -U selenium

      - name: Run Test
        run: python tests/hello_aut.py ${{ env.URL }} ${{ matrix.browser }}

      - name: Upload Screenshot
        uses: actions/upload-artifact@v4
        with:
          name: Screenshot-${{ matrix.browser }}
          path: screenshot.png

      - name: Stop Docker
        if: always()
        run: |
          docker stop selenium-${{ matrix.browser }}
          docker stop docker-apache